apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-python-flask
  labels:
    app: kiwi-python-flask
  namespace: default    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kiwi-python-flask
  template:
    metadata:
      labels:
        app: kiwi-python-flask
    spec:
      containers:
      - name: python
        image: pixelpotato/python_flask:v1.0
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
  
