apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiwi-python-flask
  name: kiwi-python-flask
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kiwi-python-flask
  sessionAffinity: None
  type: ClusterIP
